export const projects = [
  {
    id: 'uber',
    title: 'Uber Clone',
    tech: ['Node.js', 'Express.js', 'React', 'MongoDB', 'Socket.io', 'JWT', 'Tailwind', 'Google APIs'],
    description:
      'Developed a mobile-first Uber clone using the MERN Stack with real-time ride updates via Socket.io and live tracking through Google Maps API. Implemented JWT authentication, debounced Google Places API calls for performance. The frontend was built with Vite + React and styled using Tailwind CSS.',
    github: 'https://github.com/tabishkhan18/Uber',
    live: 'https://uber-mern-app.onrender.com/',
    images: [
      '/uber/1Uber.jpg',
      '/uber/2Uber.jpg',
      '/uber/3Uber.jpg',
      '/uber/4Uber.jpg',
      '/uber/5Uber.jpg',
      '/uber/6Uber.jpg',
      '/uber/7Uber.jpg',
      '/uber/8Uber.jpg',
      '/uber/9Uber.jpg',
    ],
    layout: 'info-first',
    bg: 'bg-neutral-900',
    border: '',
  },
  {
    id: 'hostelhive',
    title: 'HostelHive',
    tech: ['Node.js', 'Express.js', 'React', 'MongoDB', 'JWT', 'Tailwind CSS'],
    description:
      'Built a hostel management system using the MERN stack. Features dual JWT-authenticated portals for students and admins, invoice generation, Excel exports, mess leave requests, complaint handling, and full student management — all in a dark-themed interface using Tailwind CSS.',
    github: 'https://github.com/tabishkhan18/HostelHive',
    live: 'https://hostelhive.onrender.com/',
    images: [
      '/hostelhive/1hostelhive.jpg',
      '/hostelhive/2hostelhive.jpg',
      '/hostelhive/3hostelhive.jpg',
      '/hostelhive/4hostelhive.jpg',
      '/hostelhive/5hostelhive.jpg',
      '/hostelhive/6hostelhive.jpg',
      '/hostelhive/7hostelhive.jpg',
      '/hostelhive/8hostelhive.jpg',
      '/hostelhive/9hostelhive.jpg',
      '/hostelhive/10hostelhive.jpg',
    ],
    layout: 'image-first',
    bg: 'bg-neutral-950',
    border: 'border-y border-neutral-700',
  },
  {
    id: 'triangle',
    title: 'Triangle Calculator',
    tech: ['HTML', 'Tailwind', 'JavaScript'],
    description:
      'A responsive website created using JavaScript, allowing users to create triangles by inputting values and calculating properties like area, perimeter, and angles with interactive event handling and canvas drawing functions.',
    github: 'https://github.com/tabishkhan18/Triangle-Calculator',
    live: 'https://tabishkhan18.github.io/Triangle-Calculator',
    image: '/triangle-calculator.jpg',
    layout: 'info-first',
    bg: 'bg-neutral-900',
    border: '',
  },
];
